name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install test dependencies
        run: sudo apt-get update && sudo apt-get install -y zsh

      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: stable
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: nimble test -y
